name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - 'projects/ng-code-scanner/**'
      - '.github/workflows/publish.yml'

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      should-publish: ${{ steps.version-check.outputs.should-publish }}
      version: ${{ steps.version-check.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Get package version
        id: package-version
        run: |
          VERSION=$(node -p "require('./projects/ng-code-scanner/package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Package version: $VERSION"

      - name: Check if version exists on npm
        id: version-check
        run: |
          PACKAGE_NAME=$(node -p "require('./projects/ng-code-scanner/package.json').name")
          VERSION=${{ steps.package-version.outputs.version }}
          
          if npm view $PACKAGE_NAME@$VERSION version 2>/dev/null; then
            echo "Version $VERSION already exists on npm"
            echo "should-publish=false" >> $GITHUB_OUTPUT
          else
            echo "Version $VERSION does not exist on npm - will publish"
            echo "should-publish=true" >> $GITHUB_OUTPUT
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  publish:
    needs: check-version
    if: needs.check-version.outputs.should-publish == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build:lib:prod

      - name: Publish to npm
        run: |
          cd dist/ng-code-scanner
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "v${{ needs.check-version.outputs.version }}" -m "Release version ${{ needs.check-version.outputs.version }}"
          git push origin "v${{ needs.check-version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.check-version.outputs.version }}
          release_name: Release v${{ needs.check-version.outputs.version }}
          body: |
            Published version ${{ needs.check-version.outputs.version }} to npm
            
            Install with:
            ```bash
            npm install ng-code-scanner@${{ needs.check-version.outputs.version }}
            ```
          draft: false
          prerelease: false
